# Site settings
title: Sneha Karki
description: Web Developer from Somewhere
author: Sneha Karki
email: your-email@example.com
url: "https://your-username.github.io" # ← change this to your actual GitHub Pages URL
baseurl: "/blog"                        # ← change this if your repo is not named "blog"

# Theme
theme: minima

# Social links (optional – only add what you use)
social_links:
  github: https://github.com/yourusername
  linkedin: https://linkedin.com/in/yourusername

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Permalinks
permalink: /:title/

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
  - LICENSE

# Analytics (optional)
# google_analytics: UA-XXXXXXXXX-X

# Disqus comments (optional)
# disqus: your-disqus-shortname
