# Site settings
title: Sneha Karki
description: Web Developer from Somewhere
author: Sneha Karki
email: your-email@example.com
url: "https://your-username.github.io" # change to your GitHub Pages URL
baseurl: "/blog" # the subpath of your site, e.g. /blog

# Theme
theme: minima

# Social links (footer icons in minima)
social_links:
  github: https://github.com/barryclark/jekyll-now
  twitter: https://twitter.com/jekyllrb
  linkedin: https://linkedin.com/in/yourusername
  instagram: https://instagram.com/yourusername
  facebook: https://facebook.com/yourusername
  youtube: https://youtube.com/user/yourchannelname

# Avatar/Profile Image
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Permalinks
permalink: /:title/

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
  - LICENSE

# Analytics (optional)
# google_analytics: UA-XXXXXXXXX-X

# Disqus comments (optional)
# disqus: your-disqus-shortname
